src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 255, nullable: false)]
    private $Name;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Company;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $telephone;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->Company;
    }

    public function setCompany(string $Company): self
    {
        $this->Company = $Company;

        return $this;
    }

    public function getTelephone(): ?int
    {
        return $this->telephone;
    }

    public function setTelephone(int $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email')
            ->add('roles')
            ->add('password')
            ->add('Name')
            ->add('Company')
            ->add('telephone')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class UserController extends AbstractController
{
    #[Route('/user', name: 'app_user')]
    public function index(): Response
    {
        return $this->render('user/index.html.twig', [
            'controller_name' => 'UserController',
        ]);
    }
    #[Route('/user/business', name: 'app_business')]
    public function business(UserRepository $users): Response
    {
        return $this->render('user/businessLibrary.html.twig', [
            'users' => $users,
        ]);
    }
}

templates/user/businessLibrary.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index
{% endblock %}

{% block body %}


	<body>
		<div class="content">
			<div class="col-md-6">
				<h3 style="text-align: center">
					Welcome to your Library
				</h3><hr/></div>

			<div class="col-md-6">
				<form>
					{% for user in users %}
						<div class="form-group">
							<label for="fullName">Name</label>
							<input type="name" class="form-control" id="full_usr_name" maxlength="64" aria-describedby="Name" value="{{ app.user.name}}" readonly>
						</div><br>
						<div class="form-group">
							<label for="companyName">Company</label>
							<input type="name" class="form-control" id="company_usr_name" maxlength="64" aria-describedby="Company" value="{{ app.user.company}}" readonly>
						</div><br>
						<div class="form-group">
							<label for="emailAdress">Email</label>
							<input type="email" class="form-control" aria-describedby="Email" value="{{ app.user.email}}" readonly>
						</div><br>
						<div class="form-group">
							<label for="phoneNumber">Phonen number</label>
							<input type="phone" class="form-control" id="usr_phone_number" aria-describedby="Phone" value="{{ app.user.telephone}}" readonly>
						</div><br>
						<button type="submit" class="btn btn-primary">Exchange info</button>
						<a href="{{ path('app_user') }}" class="btn btn-primary" style="background-color:grey">Back to profile</a>
					{% endfor %}
				</form>
			</div>
		</div>
	</body>
</body></div></body>{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!
{% endblock %}

{% block body %}
	<style>
		.example-wrapper {
			margin: 1em auto;
			max-width: 800px;
			width: 95%;
			font: 18px / 1.5 sans-serif;
		}
	</style>
	{% if app.user %}
		<div class="example-wrapper">
			<h1>Welcome
				{{ app.user.name }}!
			</h1>
		</div>


		<table class="table">
			<tbody>

				<tr>
					<th>Email</th>
					<td>{{ app.user.email }}</td>
				</tr>
				<tr>
					<th>Password</th>
					<td>{{ app.user.password }}</td><br>
					<td>
						<span style="color:red">This is hashed for security purposes!</span>
					</td>
				</tr>
				<tr>
					<th>Name</th>
					<td>{{ app.user.Name }}</td>
				</tr>
				<tr>
					<th>Company</th>
					<td>{{ app.user.Company }}</td>
				</tr>
				<tr>
					<th>Telephone</th>
					<td>{{ app.user.telephone }}</td>
				</tr>
			</tbody>
		</table>

		<a href="{{ path('app_share') }}">Want to Share?</a><br>

		<a href="{{ path('app_business') }}">see business card liste</a>


	{% else %}
		<h1>
			<span style="color:red">WARNING :</span><br>You are tring to get into a page which requires authentification !
		</h1>
		You may either
		<li id="menu-item-538" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-415 current_page_item menu-item-538">
			<a href="{{ path('app_login') }}">Sign in</a>
			<br>Or create your account by clicking on "Inscription" below
		</li>
		<li id="menu-item-538" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-415 current_page_item menu-item-538">
			<a href="{{ path('register') }}">Inscription</a>
		{% endif %}
	{% endblock %}

templates/user/library.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index
{% endblock %}

{% block body %}


	<body>
		<div class="content">
			<div class="col-md-6">
				<h3 class="">
					Welcome to your Library
				</h3><hr/></div>

			<div class="col-md-6">
				<form>

					<div class="form-group">
						<label for="fullName">Name</label>
						<input type="name" class="form-control" id="full_usr_name" maxlength="64" aria-describedby="Name" value="{{ app.user.name}}" readonly>
					</div><br>
					<div class="form-group">
						<label for="companyName">Company</label>
						<input type="name" class="form-control" id="company_usr_name" maxlength="64" aria-describedby="Company" value="{{ app.user.company}}" readonly>
					</div><br>
					<div class="form-group">
						<label for="emailAdress">Email</label>
						<input type="email" class="form-control" aria-describedby="Email" value="{{ app.user.email}}" readonly>
					</div><br>
					<div class="form-group">
						<label for="phoneNumber">Phonen number</label>
						<input type="phone" class="form-control" id="usr_phone_number" aria-describedby="Phone" value="{{ app.user.telephone}}" readonly>
					</div><br>
					<button type="submit" class="btn btn-primary">Exchange info</button>
					<a href="{{ path('app_share') }}" class="btn btn-primary" style="background-color:grey">Cancel</a>

				</form>
			</div>
		</div>
	</body>
</div></body>{% endblock %}

templates/user/select.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index
{% endblock %}

{% block body %}
	<h1>Select the user with whome would you like to share info<hr/></h1>

	<table class="table">
		<thead>
			<tr>
				<th>Name</th>
			</tr>
		</thead>
		<tbody>
			{% for user in users %}
				<tr>
					<td>
						<h5 style="color:brown">{{ user.Name }}</h5>
					</td>
					<td>
						<a href="{{ path('app_selected', {'id': user.id}) }}">Select</a>

					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="8">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}